### ISSUE TITLE
 port for swagger in config

### ISSUE THREAD

**Issue by asafMasa** [MapColonies/work-standard#11]

**Comment by syncush** [comment]
I disagree, port should be specified in config, it is a env variable a runtime, it was discussed with @cl-shaharshavit-rnd .

**Comment by cl-shaharshavit-rnd** [comment]
he didn't mean the listening port.
as it run in docker the external port used can be different the the listening port.
he want to add a config of the external port so the swagger ui can send requests to the correct port
