### ISSUE TITLE
work-standard v2

### ISSUE THREAD

**Issue by CptSchnitz** [MapColonies/work-standard#40]
We would like to refactor the typescript work for improved structure and functionality.

#### Some points for improvement:
- Change docker file start to command instead of shell script. As long as the there little to none logic in the app start (1-3 commands), its better to just write it in the Dockerfile.
- README filename should be in capital letters.
- Have an example for linting using a github action 
- Add commitlint base scopes. that way its clearer to the developer what are the available scopes, and the changlog is better.
- Is confd necessary? in my opinion an app shouldn't also manage its own configuration (If we do want it managed in this way, there are better tools than confd).
- move tests folder out of src, tests are not part of the source code.
- better access log format. there are known formats for access log like Apache, we shouldn't invent our own.
- move containerConfig out of src? its also not a part of source code, and it might be better if its in root, or it's own directory.

**Comment by asafMasa** [comment]
- update to a newer node version?
- can we use newer syntax such as '??' in ts template and relay on the ts transpiler?
- add common error's types to error handling
- how to use common definitions and openapi files (such as in designated npm package - mc-models) 
- nest https://nestjs.com/ - pros cons

**Comment by syncush** [comment]
@asafMasa moving to nest means we would dump this work-standard, this repo was created to be a less opinionated alternative to nextjs.

**Comment by asafMasa** [comment]
@syncush i think we should close this issue
